version: '3.8'

services:
  api:
    build:
      context: ./suro-api/
      dockerfile: Dockerfile.prod
    image: suro-api:prod
    container_name: suro-api
    restart: unless-stopped
    environment:
      - PORT=30000
      - SURO_FRONTEND_URL=${SURO_FRONTEND_URL}
    ports:
      - ${SURO_API_PORT}:30000

  frontend:
    build:
      context: ./suro-frontend/
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_SURO_API_URL=${SURO_API_URL} # define arg here so the env var is available at build time
    image: suro-frontend:prod
    container_name: suro-frontend
    restart: unless-stopped
    ports:
      - ${SURO_FRONTEND_PORT}:80
    environment:
      - REACT_APP_SURO_API_URL=${SURO_API_URL}
