# build environment
FROM node:20.5-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm ci --silent
COPY . ./

# production environment
FROM node:20.5-alpine
WORKDIR /app
COPY --from=build /app .
COPY db.json .
EXPOSE 30000
CMD ["npm", "start"]